<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>RaveStudioAI</AssemblyName>
    <RootNamespace>RaveStudioAI</RootNamespace>
    <ApplicationIcon>cat_pumpkin_halloween_22020.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="cat_pumpkin_halloween_22020.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DocX" Version="5.0.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Medidata.RWS.NET.Standard" Version="2.0.2" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.1.0-preview.1.25608.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\ai-configs.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\analytes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\rws-configs.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\Sds\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Prompts\EditCheck\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
